global:
  scrape_interval: 15s

scrape_configs:
  - job_name: scheduler
    metrics_path: /metrics
    static_configs:
      - targets: ["consumer:8000", "producer:8000"]

  # RabbitMQ already ships a Prometheus endpoint on 15692 when the
  # rabbitmq_prometheus plugin is enabled (it is in :management images).
  - job_name: rabbitmq
    static_configs:
      - targets: ["rabbitmq:15692"]
